### PR TITLE
Add appbar element with test

### PR DESCRIPTION
**Pull request by dmitriigriazin**

### CODE REVIEW

**Comment by dsvoronin** [comment]
After #6, Push something to re-trigger checks please

**Review by dsvoronin — CHANGES_REQUESTED** [review]
Since it is the first added feature on github it requires README change
You can do it in free form, lets talk how to do it in process

**Review by dimorinny — DISMISSED** [review]

**Comment by dmitriigriazin** [comment]
@dsvoronin let's merge it, leaving Readme work after #11

**Review by dsvoronin — APPROVED** [review]

**Comment by dmitriigriazin** [comment]
What blocks this pr?

**Comment by dmitriigriazin** [comment]
`Only those with write access to this repository can merge pull requests.`

@dsvoronin you should merge it explicitly

**Pull request merged**
